### PR TITLE
Need fs-plus module

### PR DESCRIPTION
**Pull request by arunoda**

### CODE REVIEW

**Comment by jiku** [comment]
(Having to add this too, just FYI)

**Comment by tomitrescak** [comment]
Hmm, why is this needed though? I am not referencing it anywhere :/

**Comment by tomitrescak** [comment]
Guys, the plugin should be working now, please give it another go and let me know your thoughts. Sorry about the errors.

**Comment by jiku** [comment]
Weird. Can't remember the exact error msg. No issues here now at least.

**Pull request merged**
